# Generated by Django 4.2 on 2025-01-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_city_province_city_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='city_name',
            new_name='name',
        ),
    ]
