# Generated by Django 4.2 on 2025-01-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_city_name_province_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_device',
            field=models.ManyToManyField(blank=True, related_name='user_device', to='users.device'),
        ),
    ]
