# Generated by Django 4.2 on 2025-01-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_options_user_user_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_device',
        ),
    ]
